BASE_PATH:
SITE_PATH: http://blog.yinwoods.com
paginate: 10 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
encoding: utf-8
permalink: /:categories/:title.html

markdown: redcarpet

highlighter: 

name: yinwoods
title: yinwoods的个人博客

author:
  name: yinwoods
  email: yinwoods@163.com
  github: yinwoods

rss_path: rss.xml
